workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          xcodebuild -resolvePackageDependencies
      - name: Build the app
        script: |
          xcodebuild build -scheme LearningAdventure -destination 'generic/platform=iOS'
    artifacts:
      - build/ios/Debug-iphoneos/*.app
